### ISSUE TITLE
please upgrade parse-url to 3.x.x version

### ISSUE THREAD

**Issue by frankLife** [IonicaBizau/git-up#15]
`git@gitlab.xxx.com:9radio/dmax.git` doesn't work correctly with parse-url of 1.x.x version

**Comment by frankLife** [comment]
@IonicaBizau

**Comment by frankLife** [comment]
It seems upgrade  can't  fix this question . It also has a `:` colon in `full_name` field

**Comment by IonicaBizau** [comment]
Can you add examples?

**Comment by frankLife** [comment]
```
{ protocols: [],
  protocol: 'ssh',
  port: 9,
  resource: 'gitlab.xxx.com',
  user: 'git',
  pathname: '/dmax.git',
  hash: '',
  search: '',
  href: 'git@gitlab.xxx.com:9radio/dmax.git',
  token: '',
  toString: [Function],
  source: 'xxx.com',
  git_suffix: true,
  name: 'dmax',
  owner: 'git',
  ref: '',
  filepathtype: '',
  filepath: '',
  organization: 'git',
  full_name: 'git/dmax' }
```
by  
```
const GitUrlParse = require("git-url-parse");
console.log(GitUrlParse('git@gitlab.xxx.com:9radio/dmax.git'))
```
with git-url-parse@10.1.0

**Comment by frankLife** [comment]
@IonicaBizau please fix this, our system deeply depends on this great module.

**Comment by frankLife** [comment]
When I upgrade the `git-url-parse` after close this issue, I get the result: 

```
{ protocols: [ 'http' ],
  protocol: 'ssh',
  port: null,
  resource: 'xxx',
  user: 'git',
  pathname: '/:9radio/dmax.git',
  hash: '',
  search: '',
  href: 'http://git@xxx/:9radio/dmax.git',
  query: {},
  token: '',
  toString: [Function],
  source: 'xxx',
  git_suffix: true,
  name: 'dmax',
  owner: ':9radio',
  commit: undefined,
  ref: '',
  filepathtype: '',
  filepath: '',
  organization: ':9radio',
  full_name: ':9radio/dmax' }
```
It looks the colon `:` in `full_name` and `owner` field are wrong

**Comment by AMDvsTMD** [comment]
don't update when update it is wrong

**Comment by AMDvsTMD** [comment]
> When I upgrade the `git-url-parse` after this issue was closed, I get the result:
> 
> ```
> { protocols: [ 'http' ],
>   protocol: 'ssh',
>   port: null,
>   resource: 'xxx',
>   user: 'git',
>   pathname: '/:9radio/dmax.git',
>   hash: '',
>   search: '',
>   href: 'http://git@xxx/:9radio/dmax.git',
>   query: {},
>   token: '',
>   toString: [Function],
>   source: 'xxx',
>   git_suffix: true,
>   name: 'dmax',
>   owner: ':9radio',
>   commit: undefined,
>   ref: '',
>   filepathtype: '',
>   filepath: '',
>   organization: ':9radio',
>   full_name: ':9radio/dmax' }
> ```
> It looks the colon `:` in `full_name` and `owner` field are wrong
> 
> @IonicaBizau

you should test right then push otherwise will affect others

**Comment by IonicaBizau** [comment]
@AMDvsTMD Indeed! But in this case, the tests were wrong and failing silently 🙈 Should be fine now! 🚀
