### ISSUE TITLE
`git` type URL are parsed incorrectily

### ISSUE THREAD

**Issue by pvdlg** [IonicaBizau/git-up#17]
```js
const gitUp = require('git-up');
gitUp('git@github.com:IonicaBizau/git-stats.git');
// { protocols: [ 'http' ],
//   protocol: 'ssh',
//   port: null,
//   resource: 'github.com',
//   user: 'git',
//   pathname: '/:IonicaBizau/git-stats.git',
//   hash: '',
//   search: '',
//   href: 'http://git@github.com/:IonicaBizau/git-stats.git',
//   query: {},
//   token: '' }
```

`href` is wrongly set to `http://git@github.com/:IonicaBizau/git-stats.git`
`protocols` is wrongly set to `['http']`

This is because `git-up` calls `parse-url` which calls `normalize-url`.
`normalize-url` throws an error for `git` URL:
```js
const normalizeUrl = require('normalize-url');
normalizeUrl('git@github.com:IonicaBizau/git-stats.git');
[ERR_INVALID_URL]: Invalid URL: http:git@github.com:IonicaBizau/git-stats.git
```

**Comment by IonicaBizau** [comment]
Thanks for reporting this and sorry for the inconvenience—I just discovered that there was a try-catch in the tests, which was making them to pass, all. 🙈 

I did some breaking changes in `parse-url`, `parse-path` and `git-up` and I mentioned you to review them

**Comment by pvdlg** [comment]
@IonicaBizau, any update on this? I reviewed your PRs and I think they are good to go. Do you know when you can merge and release them? This issue is impacting a lot of folks... Thanks!

**Comment by IonicaBizau** [comment]
@pvdlg I got the chance to work on this finally. Released the major versions of the dependencies, releasing this now as well. 🚀

**Comment by pvdlg** [comment]
Thanks!
