### ISSUE TITLE
normalize-url v3 is vulnerable

### ISSUE THREAD

**Issue by lykims** [IonicaBizau/git-up#24]
Following the issue https://github.com/IonicaBizau/parse-url/issues/19, `git-up` should have the latest version of `parse-url` as well.

Details about the security issue: https://www.npmjs.com/advisories/1755

**Comment by IonicaBizau** [comment]
This should be fixed now. 😄 Thank you!

**Comment by lykims** [comment]
Hi @IonicaBizau!

From your comment https://github.com/IonicaBizau/parse-url/issues/19#issuecomment-870464466, should `git-up` have another version as well?

I also created the issue https://github.com/IonicaBizau/git-url-parse/issues/130.

**Comment by IonicaBizau** [comment]
Hi @lykims! I am not sure what to do here: `normalize-url` should get a patch for Safari, ideally... `git-up` now uses `parse-url@6.x.x`.
